# Site settings
title: Ketan Somvanshi
description: Backend Developer | Portfolio
baseurl: "/KetanSomvanshi" # Set this if your site is hosted under a subpath, e.g., /my-site/
url: "https://ketansomvanshi.github.io" # Set your site URL

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight # Change the theme to "jekyll-theme-midnight"

# GitHub Pages specific configuration
remote_theme: ""
plugins:
  - jekyll-feed

# Exclude files/folders from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Customize the URL structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# GitHub Pages specific configuration
github:
  repository: KetanSomvanshi/KetanSomvanshi
  baseurl: "/KetanSomvanshi" # Set this if your site is hosted under a subpath, e.g., /my-site/
