# Site settings
title: Your Site Title
description: Your Site Description
baseurl: "" # Set this if your site is hosted under a subpath, e.g., /my-site/
url: "" # Set your site URL

# Build settings
markdown: kramdown
theme: midnight # You can change the theme here, or install custom themes

# GitHub Pages specific configuration
remote_theme: # Specify the remote theme if you're using one
  - "mmistakes/minimal-mistakes" # Example remote theme

plugins:
  - jekyll-feed

# Exclude files/folders from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Customize the URL structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# GitHub Pages specific configuration
github:
  repository: KetanSomvanshi/KetanSomvanshi
  baseurl: "" # Set this if your site is hosted under a subpath, e.g., /my-site/
